# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"	
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.69.5"
  config.vm.hostname = "exploit"
  config.vm.provision "shell", inline: <<-SHELL
    uptime
    echo "up"
  SHELL
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
  end
end
