# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "master-exploit" do |master|
    master.vm.network "private_network", ip: "192.168.69.5"
    master.vm.hostname = "master-exploit"
  end
  (1..2).each do |i|
    config.vm.define "slave-exploit-#{i}" do |slave|
      slave.vm.network "private_network", ip: "192.168.69.1#{i}"
      slave.vm.hostname = "slave-exploit-#{i}"
      slave.vm.provision "slave-only", type: "shell", inline: <<-EOF
	echo "up inside"
      EOF
    end
  end
end
